# config/meta.yml

meta_product_name: "PuP"
meta_title: "PuP - Find your Best Friend"
meta_description: "Connecting Dog Lovers with Reputable Breeders"
meta_image: "PuP_meta_img1.png" # should exist in `app/assets/images/`
